import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { getServerSession } from "@/lib/serverSession";

function jsonError(message: string, status = 400) {
  return NextResponse.json({ error: message }, { status });
}

export async function POST(req: Request) {
  const session = await getServerSession();
  if (!session?.distributorId) return jsonError("Unauthorized", 401);

  const body = await req.json();
  const sourceOrderId = String(body?.orderId || "");
  if (!sourceOrderId) return jsonError("Missing orderId", 400);

  const source = await prisma.order.findFirst({
    where: { id: sourceOrderId, distributorId: session.distributorId },
    include: { items: true },
  });
  if (!source) return jsonError("Order not found", 404);

  let meta: any = {};
  try {
    meta = source.notes ? JSON.parse(source.notes) : {};
  } catch {
    meta = {};
  }

  // remove old signature etc.
  if (meta.signature) delete meta.signature;

  // mark repeat
  meta.repeatedFrom = sourceOrderId;
  meta.poNumber = null; // new PO will be generated by /api/orders/next-po on client
  meta.poDate = null;

  // copy itemsMeta if available
  const itemsMeta = Array.isArray(meta.itemsMeta) ? meta.itemsMeta : null;

  const newOrder = await prisma.order.create({
    data: {
      distributorId: session.distributorId,
      status: "RECEIVED",
      notes: JSON.stringify(meta),
      items: {
        create: source.items.map((it, idx) => ({
          productId: it.productId,
          variantId: (it as any).variantId ?? (itemsMeta?.[idx]?.variantId ?? null),
          qty: it.qty,
          unitPrice: it.unitPrice,
        })),
      },
    },
    include: { items: true },
  });

  return NextResponse.json({ ok: true, order: newOrder });
}